version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonar
      - run:
          name: upload code coverage
          command: gradle test jacocoTestReport sonar

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud